import { Faction } from '../Faction'

export enum FactionCardType {
  NihilistPenguin = 1,
  LunarWendigo,
  ShieldOfDawn,
  IcePaladin,
  Eagle,
  PaladinOfTheGuard,
  SnowGriffin,
  Gabriel,
  IceGolem,
  FortressOfMyjir,
  IceMeteor,
  WinterProtects,
  Teleportation,
  Blizzard,
  DeathCrawler,
  Xenodon,
  NakkaArcher,
  SenileYhdorian,
  Hexacarias,
  CarnivorousPlant,
  Banshee,
  Behemoth,
  MountedBanshee,
  WrathOfTheForest,
  ThreeOfLife,
  EarthQuake,
  UnstableGrowth,
  NaturalCamouflage,
  Mimicry,
  DrunkKnight,
  Infantryman,
  Phalanx,
  Ballista,
  Champion,
  GreyHorseman,
  SiegeTower,
  HeroOfTheBattleOfNerz,
  TheSeneschal,
  AvalonFortress,
  Warcry,
  ShieldWall,
  HorseOfAvalon,
  ScuttleJaw,
  SwampOgre,
  SwampTroll,
  Berserker,
  PlagueCollector,
  Slayer,
  ForgePatriarch,
  AbominableHydra,
  ChildEater,
  WesternForge,
  FireLighning,
  Firestorm,
  TheFear,
  ForcedExile
}

const Whitelands = [
  FactionCardType.NihilistPenguin,
  FactionCardType.LunarWendigo,
  FactionCardType.ShieldOfDawn,
  FactionCardType.IcePaladin,
  FactionCardType.Eagle,
  FactionCardType.PaladinOfTheGuard,
  FactionCardType.SnowGriffin,
  FactionCardType.Gabriel,
  FactionCardType.IceGolem,
  FactionCardType.FortressOfMyjir,
  FactionCardType.IceMeteor,
  FactionCardType.WinterProtects,
  FactionCardType.Teleportation,
  FactionCardType.Blizzard
]

const Nakkas = [
  FactionCardType.DeathCrawler,
  FactionCardType.Xenodon,
  FactionCardType.NakkaArcher,
  FactionCardType.SenileYhdorian,
  FactionCardType.Hexacarias,
  FactionCardType.CarnivorousPlant,
  FactionCardType.Banshee,
  FactionCardType.Behemoth,
  FactionCardType.MountedBanshee,
  FactionCardType.WrathOfTheForest,
  FactionCardType.ThreeOfLife,
  FactionCardType.EarthQuake,
  FactionCardType.UnstableGrowth,
  FactionCardType.NaturalCamouflage,
  FactionCardType.Mimicry
]

const GreyOrder = [
  FactionCardType.DrunkKnight,
  FactionCardType.Infantryman,
  FactionCardType.Phalanx,
  FactionCardType.Ballista,
  FactionCardType.Champion,
  FactionCardType.GreyHorseman,
  FactionCardType.SiegeTower,
  FactionCardType.HeroOfTheBattleOfNerz,
  FactionCardType.TheSeneschal,
  FactionCardType.AvalonFortress,
  FactionCardType.Warcry,
  FactionCardType.ShieldWall,
  FactionCardType.HorseOfAvalon
]

const Blight = [
  FactionCardType.ScuttleJaw,
  FactionCardType.SwampOgre,
  FactionCardType.SwampTroll,
  FactionCardType.Berserker,
  FactionCardType.PlagueCollector,
  FactionCardType.Slayer,
  FactionCardType.ForgePatriarch,
  FactionCardType.AbominableHydra,
  FactionCardType.ChildEater,
  FactionCardType.WesternForge,
  FactionCardType.FireLighning,
  FactionCardType.Firestorm,
  FactionCardType.TheFear,
  FactionCardType.ForcedExile
]

export const CardsByFaction: Record<Faction, FactionCardType[]> = {
  [Faction.Whitelands]: Whitelands,
  [Faction.Nakka]: Nakkas,
  [Faction.GrayOrder]: GreyOrder,
  [Faction.Blight]: Blight
}
